# SAM Configuration File
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "parque-explora-survey-dev"
s3_prefix = "parque-explora-survey"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev ApiKeyValue=REPLACE_WITH_API_GATEWAY_KEY"
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "parque-explora-survey-dev"
parameter_overrides = "Environment=\"dev\" ApiKeyValue=\"REPLACE_WITH_API_GATEWAY_KEY\" OpenAIApiKey=\"REPLACE_WITH_OPENAI_API_KEY\" OpenAIModel=\"gpt-4o-mini\""
image_repositories = []
disable_rollback = true
